server:
  port: 8011

spring:
  application:
    name: employee-service
    
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    
    
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG