server:
  port: ${PORT:8761}  # Indicate the default PORT where this service will be started
  
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false         #telling the server not to register himself in the 
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
  server:
    wait-time-in-ms-when-sync-empty: 0         #wait time for subsequent sync
