spring:
  application:
    name: app-tutorial-service

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-ui

  data:
    mongodb:
      uri: mongodb+srv://peddarajumaddha:UHBuhb2021@sandbox.fzxqi.mongodb.net/test?retryWrites=true&w=majority
  logging:
    level:
      org.springframework.data.mongodb: debug
