server:
  port: 5000


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:            # The SQL dialect makes Hibernate generate better SQL for the chosen database
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-ui
  sql:              # Initialize the datasource with available DDL and DML scripts
    init:
      mode: always

#  jackson:
#    serialization: false
#    time-zone: UTC

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DBUG
